[tool.black]
line-length = 120
skip-string-normalization = true
include = '\.pyi?$'
target-version = ['py39']
force-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''